export { Header } from "./Header";
export { MainLayer } from "./Main";
export { TaskLayer } from "./Task";
export { StagesLayer } from "./Stages";
export { DesignLayer } from "./Design";
export { FeedbackLayer } from "./Feedback";
export { QuestionsLayer } from "./Questions";
export { DifficultLayer } from "./Difficult";
export { CooperationLayer } from "./Cooperation";
